apiVersion: apps/v1
kind: Deployment
metadata:
  name: emporium
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emporium
  template:
    metadata:
      labels:
        app: emporium
    spec:
      imagePullSecrets:
        - name: docker-hub-creds
      containers:
        - name: emporium
          image: lutfhanbit/emporium:dev.v51
          ports:
            - containerPort: 80
