apiVersion: apps/v1
kind: Deployment
metadata:
  name: emporium
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emporium
  template:
    metadata:
      labels:
        app: emporium
    spec:
      containers:
        - name: emporium
          image: lutfhanbit/emporium:24
          resources:
            requests:
              memory: "64Mi"
              cpu: "30m"
            limits:
              memory: "2048Mi"
              cpu: "1"
          ports:
            - containerPort: 80
